import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "react-hot-toast";
import { Navbar03 } from "@/ui/shadcn-io/navbar-03";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100svh] flex flex-col pb-10 gap-6`}
      >
        <Navbar03 className="shrink-0" />
        <main className="flex-1 min-h-0 flex items-stretch">{children}</main>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
